name: Automated testing

run-name: ${{ github.actor }} is testing QNetGame 🚀

on: [push]

jobs:
  Run-Test-Suite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: PYTHONPATH=src:. pytest tests/ -q

      - name: Start of the job
        run: echo "🚀 Starting the automated testing job for QNetGame!"

      - run: echo "🍏 This job's status is ${{ job.status }}."
